### ISSUE TITLE
Missed block not propagated due to too many sensations

### ISSUE THREAD

**Issue by thofra** [floh-bhaptics/BeatSaber_OWO#2]
First of all, GREAT WORK! Thank you so much.
But one issue: in general I like the idea of the sensations for arms and shoulders when slicing a block, but this is creating lots of sensations and other sensations like missed blocks are skipped (at least for Expert and Expert+ maps with lots of block).
Proposal:
- remove the sensation when slicing a block
- consider adding a sensation of "wind" when walls are passing (w/o touching/hitting them)
- consider adding a sensation when failing a level (I propose belly plus shoulders)

**Comment by floh-bhaptics** [comment]
I have to be frank with you: I never understood why people would want to play this exact game with an OWO vest. :-D I just put it up for a vote... And the OWO team suggested what effects should be included.

As a quick fix, you can change the intensity of the slice effects to zero in the app settings for Beat Saber, since those are all "baked sensations", so you can adjust them individually. But that won't fix the problem that OWO can't play two sensations at once and if another one gets sent quickly, missed notes and other effects might be swallowed.

So I suggest that I will make a second mod version that doesn't include slice effects. Adding a level fail is certainly a good idea. I'll have to dig into the code to see if I can find a good mod hook for walls whizzing by, I can't promise that this is possible. Thanks for the input!

**Comment by floh-bhaptics** [comment]
Alright. I just added a second build to the newest release (3.1.0) called "NoSlice" that does not trigger any Slice sensations. This should do the trick. ;-) I also added a Level Failed sensation and play the "Start" sensation again if a level is cleared. Have fun! And thanks again for the idea!

**Comment by thofra** [comment]
Unfortunately, the new "NoSlice" does not provide any sensations. After connecting from MyOWO, it shows "connected to Beatsaber" but there is only the stop button and no calibration button for sensations. Sensations menu is empty, and the game does not trigger any sensation.
Additionally, one question related to Start sensation. Is it supposed to be played when the game starts, or when a map starts?

**Comment by floh-bhaptics** [comment]
Alright. I finally fixed it. Apparently, OWO had introduced some issues with their newest SDK, and the build automatically upgraded. Sorry, I currently don't have an OWO skin for testing at home, so I am flying blind here. :-) But I checked and I can definitely see that the mod connects properly, has all the necessary sensations, and does send "something" when playing the game... So, try the updated version 3.1.1, that should do the trick, I am fairly sure.

The "Start" sensation only plays once on StartUp, I added that in the very beginning as an easy check that the mod works. It might be swallowed by the connection though, if it gets sent before the vest connects. A lot changed there on the OWO side since I made the mod originally. I can check if it's possible to add a sensation when starting a song, but I'm not sure that this adds a lot to the immersion...
